"""Zentrale Definition der Garderoben-Kategorien und Metadaten-Optionen.

Diese Werte werden sowohl fuer die KI-Extraktion (als erlaubte Werte)
als auch im Frontend zur Bestaetigung / Bearbeitung verwendet.
"""

# Hauptkategorien eines Kleidungsstuecks (hierarchisch gruppiert)
CATEGORY_GROUPS = [
    {
        "group": "Oberteile",
        "items": [
            "T-Shirt",
            "Hemd",
            "Bluse",
            "Poloshirt",
            "Longsleeve",
            "Tanktop",
            "Top",
            "Crop-Top",
        ],
    },
    {
        "group": "Pullover & Hoodies",
        "items": [
            "Pullover",
            "Hoodie",
            "Sweatshirt",
            "Cardigan",
            "Rollkragenpullover",
            "Strickjacke",
        ],
    },
    {
        "group": "Hosen",
        "items": [
            "Jeans",
            "Chino",
            "Stoffhose",
            "Cargohose",
            "Jogginghose",
            "Leggins",
            "Shorts",
        ],
    },
    {
        "group": "Röcke & Kleider",
        "items": [
            "Rock",
            "Maxirock",
            "Minirock",
            "Kleid",
            "Maxikleid",
            "Midikleid",
            "Minikleid",
        ],
    },
    {
        "group": "Jacken & Mäntel",
        "items": [
            "Jacke",
            "Jeansjacke",
            "Lederjacke",
            "Bomberjacke",
            "Übergangsjacke",
            "Mantel",
            "Trenchcoat",
            "Wintermantel",
            "Parka",
            "Daunenjacke",
            "Blazer",
            "Weste",
            "Softshell",
            "Regenjacke",
        ],
    },
    {
        "group": "Anzüge & Sets",
        "items": [
            "Anzug",
            "Anzughose",
            "Anzugweste",
            "Kostüm",
            "Hosenanzug",
            "Jumpsuit",
            "Overall",
        ],
    },
    {
        "group": "Schuhe",
        "items": [
            "Sneaker",
            "Laufschuhe",
            "Turnschuhe",
            "Stiefel",
            "Stiefeletten",
            "Chelsea-Boots",
            "Halbschuhe",
            "Schnürschuhe",
            "Loafer",
            "Mokassins",
            "Sandalen",
            "Flip-Flops",
            "Ballerinas",
            "Pumps",
            "High Heels",
            "Hausschuhe",
        ],
    },
    {
        "group": "Accessoires",
        "items": [
            "Gürtel",
            "Mütze",
            "Beanie",
            "Cap",
            "Hut",
            "Schal",
            "Tuch",
            "Handschuhe",
            "Krawatte",
            "Fliege",
            "Einstecktuch",
            "Tasche",
            "Handtasche",
            "Umhängetasche",
            "Rucksack",
            "Clutch",
            "Brille",
            "Sonnenbrille",
            "Uhr",
            "Schmuck",
            "Halskette",
            "Armband",
            "Ring",
            "Ohrringe",
        ],
    },
    {
        "group": "Unterwäsche & Basics",
        "items": [
            "Unterwäsche",
            "Unterhose",
            "BH",
            "Socken",
            "Strumpfhose",
            "Feinstrumpfhose",
            "Unterhemd",
        ],
    },
    {
        "group": "Sport & Freizeit",
        "items": [
            "Sportshirt",
            "Sporttop",
            "Sporthose",
            "Laufhose",
            "Sport-BH",
            "Trainingsanzug",
            "Badeanzug",
            "Bikini",
            "Badehose",
            "Bademantel",
        ],
    },
    {
        "group": "Sonstiges",
        "items": [
            "Nachtwäsche",
            "Schlafanzug",
            "Morgenmantel",
            "Sonstiges",
        ],
    },
]

# Flache Liste aller Kategorien (fuer die KI und DB-Validierung)
CATEGORIES = [item for group in CATEGORY_GROUPS for item in group["items"]]

# Kategorienspezifische Detail-Felder fuer Schritt 2
CATEGORY_DETAILS = {
    # Oberteile
    "T-Shirt": ["kragenform", "aermellänge", "passform"],
    "Hemd": ["kragenform", "aermellänge", "verschluss", "passform"],
    "Bluse": ["kragenform", "aermellänge", "verschluss", "passform"],
    "Poloshirt": ["kragenform", "aermellänge"],
    "Longsleeve": ["kragenform", "passform"],
    "Tanktop": ["trägerart"],
    "Top": ["trägerart", "passform"],
    "Crop-Top": ["trägerart"],
    # Pullover
    "Pullover": ["kragenform", "strickart", "passform"],
    "Hoodie": ["kapuze", "verschluss", "passform"],
    "Sweatshirt": ["kragenform", "passform"],
    "Cardigan": ["verschluss", "länge"],
    "Rollkragenpullover": ["strickart"],
    "Strickjacke": ["verschluss", "länge", "strickart"],
    # Hosen
    "Jeans": ["schnitt", "waschung", "stretch"],
    "Chino": ["schnitt", "bundart"],
    "Stoffhose": ["schnitt", "bügelfalte"],
    "Cargohose": ["schnitt", "anzahl_taschen"],
    "Jogginghose": ["bund", "passform"],
    "Leggins": ["länge", "kompression"],
    "Shorts": ["länge", "schnitt"],
    # Röcke & Kleider
    "Rock": ["länge", "schnitt", "bund"],
    "Maxirock": ["schnitt", "schlitz"],
    "Minirock": ["schnitt"],
    "Kleid": ["länge", "schnitt", "aermellänge", "ausschnitt"],
    "Maxikleid": ["schnitt", "aermellänge", "ausschnitt"],
    "Midikleid": ["schnitt", "aermellänge", "ausschnitt"],
    "Minikleid": ["schnitt", "aermellänge", "ausschnitt"],
    # Jacken
    "Jacke": ["verschluss", "futter", "kapuze", "länge"],
    "Jeansjacke": ["verschluss", "waschung", "passform"],
    "Lederjacke": ["lederart", "verschluss", "futter"],
    "Bomberjacke": ["verschluss", "futter"],
    "Übergangsjacke": ["verschluss", "wasserabweisend", "kapuze"],
    "Mantel": ["länge", "verschluss", "futter", "kragen"],
    "Trenchcoat": ["länge", "gürtel", "futter"],
    "Wintermantel": ["füllung", "kapuze", "wasserabweisend"],
    "Parka": ["füllung", "kapuze", "länge"],
    "Daunenjacke": ["füllung", "kapuze", "packbar"],
    "Blazer": ["knöpfe", "futter", "passform"],
    "Weste": ["verschluss", "futter"],
    "Softshell": ["wasserabweisend", "kapuze", "atmungsaktiv"],
    "Regenjacke": ["wasserdicht", "kapuze", "versiegelte_nähte"],
    # Schuhe
    "Sneaker": ["verschluss", "sohlenart", "obermaterial"],
    "Laufschuhe": ["dämpfung", "sohlenart", "atmungsaktiv"],
    "Turnschuhe": ["verschluss", "sohlenart"],
    "Stiefel": ["absatzhöhe", "schafthöhe", "verschluss", "profil"],
    "Stiefeletten": ["absatzhöhe", "verschluss"],
    "Chelsea-Boots": ["absatzhöhe", "elastik_einsatz"],
    "Halbschuhe": ["verschluss", "absatzhöhe"],
    "Schnürschuhe": ["absatzhöhe", "sohlenart"],
    "Loafer": ["absatzform"],
    "Mokassins": ["sohlenart"],
    "Sandalen": ["verschluss", "absatzhöhe", "riemen"],
    "Flip-Flops": ["sohlenart"],
    "Ballerinas": ["verschluss"],
    "Pumps": ["absatzhöhe", "zehenform"],
    "High Heels": ["absatzhöhe", "absatzform", "zehenform"],
    "Hausschuhe": ["verschluss", "sohlenart"],
    # Accessoires
    "Gürtel": ["breite", "verschluss", "länge"],
    "Mütze": ["art", "futter"],
    "Beanie": ["umschlag"],
    "Cap": ["schild", "verschluss"],
    "Hut": ["krempe", "krone"],
    "Schal": ["länge", "breite"],
    "Tuch": ["größe", "befestigung"],
    "Handschuhe": ["futter", "touchscreen"],
    "Krawatte": ["breite", "länge"],
    "Fliege": ["art"],
    "Einstecktuch": ["größe", "material"],
    "Tasche": ["verschluss", "größe", "riemen"],
    "Handtasche": ["verschluss", "größe", "henkel"],
    "Umhängetasche": ["verschluss", "größe", "riemen"],
    "Rucksack": ["volumen", "laptop_fach", "verschluss"],
    "Clutch": ["verschluss", "größe"],
    "Brille": ["form", "gestell", "gläser"],
    "Sonnenbrille": ["form", "uv_schutz", "polarisiert"],
    "Uhr": ["art", "armband", "wasserdicht"],
    "Schmuck": ["art", "verschluss"],
    "Halskette": ["länge", "verschluss", "anhänger"],
    "Armband": ["verschluss", "größe"],
    "Ring": ["größe", "stein"],
    "Ohrringe": ["verschluss", "länge"],
    # Anzüge & Sets
    "Anzug": ["knöpfe", "passform", "teilig"],
    "Anzughose": ["schnitt", "bügelfalte"],
    "Anzugweste": ["knöpfe", "passform"],
    "Kostüm": ["teilig", "passform", "länge"],
    "Hosenanzug": ["teilig", "passform"],
    "Jumpsuit": ["verschluss", "beinlänge", "passform"],
    "Overall": ["verschluss", "träger"],
    # Unterwäsche & Basics
    "Unterwäsche": ["passform", "bund"],
    "Unterhose": ["schnitt", "bund"],
    "BH": ["verschluss", "träger", "polsterung"],
    "Socken": ["länge", "bund"],
    "Strumpfhose": ["denier", "bund"],
    "Feinstrumpfhose": ["denier", "naht"],
    "Unterhemd": ["träger", "länge"],
    # Sport & Freizeit
    "Sportshirt": ["passform", "atmungsaktiv", "feuchtigkeitsableitend"],
    "Sporttop": ["träger", "passform"],
    "Sporthose": ["länge", "passform", "taschen"],
    "Laufhose": ["länge", "kompression", "reflektoren"],
    "Sport-BH": ["support", "träger", "polsterung"],
    "Trainingsanzug": ["teilig", "passform"],
    "Badeanzug": ["schnitt", "träger"],
    "Bikini": ["oberteil", "unterteil"],
    "Badehose": ["länge", "schnitt"],
    "Bademantel": ["länge", "verschluss", "kapuze"],
    # Sonstiges
    "Nachtwäsche": ["teilig", "länge"],
    "Schlafanzug": ["teilig", "länge"],
    "Morgenmantel": ["länge", "verschluss", "gürtel"],
    "Sonstiges": [],
}

# Stil / Anlass-Charakter
STYLES = [
    "elegant",
    "schick",
    "leger",
    "sportlich",
    "business",
    "casual",
    "festlich",
    "vintage",
    "streetwear",
    "minimalistisch",
    "rockig",
    "romantisch",
]

# Anlaesse fuer die die das Teil geeignet ist
OCCASIONS = [
    "Alltag",
    "Büro",
    "Business",
    "Sport",
    "Fitness",
    "Party",
    "Club",
    "Date",
    "Hochzeit",
    "Feier",
    "Urlaub",
    "Strand",
    "Zuhause",
    "Freizeit",
]

# Passende Jahreszeiten
SEASONS = [
    "Frühling",
    "Sommer",
    "Herbst",
    "Winter",
    "ganzjährig",
]

# Materialien / Texturen
MATERIALS = [
    "Baumwolle",
    "Bio-Baumwolle",
    "Leinen",
    "Wolle",
    "Merinowolle",
    "Kaschmir",
    "Alpaka",
    "Mohair",
    "Angora",
    "Denim",
    "Jeansstoff",
    "Leder",
    "Kunstleder",
    "Wildleder",
    "Nubukleder",
    "Seide",
    "Satin",
    "Chiffon",
    "Organza",
    "Taft",
    "Polyester",
    "Viskose",
    "Lyocell",
    "Modal",
    "Tencel",
    "Nylon",
    "Polyamid",
    "Elasthan",
    "Spandex",
    "Lycra",
    "Strick",
    "Grobstrick",
    "Feinstrick",
    "Fleece",
    "Cord",
    "Samt",
    "Velours",
    "Canvas",
    "Segeltuch",
    "Mesh",
    "Netz",
    "Jersey",
    "Interlock",
    "Ripp",
    "Sweat",
    "French Terry",
    "Frottee",
    "Flanell",
    "Chambray",
    "Tweed",
    "Twill",
    "Gabardine",
    "Popeline",
    "Batist",
    "Seersucker",
    "Crêpe",
    "Bouclé",
    "Jacquard",
    "Brokat",
    "Spitze",
    "Tüll",
    "Neopren",
    "Softshell",
    "Hardshell",
    "Gore-Tex",
    "Daunen",
    "Kunstfaser-Füllung",
    "Fell",
    "Kunstfell",
    "Pelz",
    "Kunstpelz",
    "Gummi",
    "Latex",
    "PVC",
    "Wachstuch",
    "Loden",
    "Filz",
    "Mikrofaser",
    "Bambus",
    "Hanf",
    "Ramie",
    "Jute",
    "Raffia",
    "unbekannt",
]
